### PR TITLE
config_sshd option for allowing agent forwarding

### PR DESCRIPTION
**Pull request by adamdunkley**

### CODE REVIEW

**Comment by whamilton42** [comment]
+1

Is there any reason this can't be accepted? (I've found a lot of Chef cookbook only allow certain attributes to be set, which results in this sort of piecemeal addition later on.)

**Comment by adamdunkley** [comment]
A better way might actually be to allow arbitrary configuration overrides by putting something at the end of the `*/sshd_config.erb` files:

```
<% @directives.sort_by { |key, val| key }.each do |directive, value| -%>
<%= "#{directive} #{value}" %>
<% end -%>
```

Where the directives variable comes is passed to the template from some attribute like `default['openssh']['configuration']  = {}` that can be added to.

This idea is borrowed from https://github.com/opscode-cookbooks/php

**Comment by adamdunkley** [comment]
Ok, updated this now so that it works as I described.

@fnichol Any chance we could get this merged down? It would save me from maintaining my branch

**Comment by fnichol** [comment]
# Upstream Development Status Of The OpenSSH Chef Cookbook

Hi there.

First off, I'm sorry this reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the canonical source for the OpenSSH Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:
- Source code: https://github.com/chef-cookbooks/openssh
- Supermarket: https://supermarket.chef.io/cookbooks/openssh

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!

**Pull request closed without merging**
